import { useMemo, useState, type ReactNode } from 'react'
import './App.css'

type Screen = 'Dashboard' | 'Transactions' | 'Analytics' | 'Portfolio' | 'Settings'
type IconName = 'grid' | 'swap' | 'chart' | 'briefcase' | 'settings' | 'sun' | 'moon' | 'search' | 'bell' | 'arrow' | 'plus' | 'chevron' | 'trend' | 'wallet' | 'menu' | 'close'
type Transaction = { name: string; category: string; date: string; amount: number; type: 'income' | 'expense'; icon: string; color: string }

const transactions: Transaction[] = [
  { name: 'Stripe payout', category: 'Income', date: 'Today, 10:42 AM', amount: 4200, type: 'income', icon: 'S', color: 'blue' },
  { name: 'Whole Foods Market', category: 'Groceries', date: 'Today, 08:18 AM', amount: 86.42, type: 'expense', icon: 'W', color: 'green' },
  { name: 'Figma Professional', category: 'Software', date: 'Yesterday', amount: 15, type: 'expense', icon: 'F', color: 'purple' },
  { name: 'Airbnb', category: 'Travel', date: 'Sep 14, 2025', amount: 312.8, type: 'expense', icon: 'A', color: 'orange' },
  { name: 'Freelance invoice', category: 'Income', date: 'Sep 13, 2025', amount: 1850, type: 'income', icon: 'F', color: 'blue' },
  { name: 'Notion', category: 'Software', date: 'Sep 12, 2025', amount: 10, type: 'expense', icon: 'N', color: 'dark' },
]

const navItems: { label: Screen; icon: IconName }[] = [
  { label: 'Dashboard', icon: 'grid' }, { label: 'Transactions', icon: 'swap' }, { label: 'Analytics', icon: 'chart' }, { label: 'Portfolio', icon: 'briefcase' }, { label: 'Settings', icon: 'settings' },
]

function Icon({ name, size = 18 }: { name: IconName; size?: number }) {
  const common = { width: size, height: size, viewBox: '0 0 24 24', fill: 'none', 'aria-hidden': true } as const
  if (name === 'grid') return <svg {...common}><rect x="4" y="4" width="6" height="6" rx="1" stroke="currentColor" strokeWidth="1.7" /><rect x="14" y="4" width="6" height="6" rx="1" stroke="currentColor" strokeWidth="1.7" /><rect x="4" y="14" width="6" height="6" rx="1" stroke="currentColor" strokeWidth="1.7" /><rect x="14" y="14" width="6" height="6" rx="1" stroke="currentColor" strokeWidth="1.7" /></svg>
  if (name === 'swap') return <svg {...common}><path d="M7 7h11m0 0-3-3m3 3-3 3M17 17H6m0 0 3-3m-3 3 3 3" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" /></svg>
  if (name === 'chart') return <svg {...common}><path d="M5 19V9m7 10V5m7 14v-7" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" /></svg>
  if (name === 'briefcase') return <svg {...common}><rect x="4" y="7" width="16" height="12" rx="2" stroke="currentColor" strokeWidth="1.7" /><path d="M9 7V5h6v2M4 12h16M10 12v2h4v-2" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" /></svg>
  if (name === 'settings') return <svg {...common}><path d="M12 8.5a3.5 3.5 0 1 0 0 7 3.5 3.5 0 0 0 0-7Z" stroke="currentColor" strokeWidth="1.7" /><path d="m19.4 15 .1.1a1.8 1.8 0 0 1-2.5 2.5l-.1-.1a1.8 1.8 0 0 0-3.1 1.3v.2a1.8 1.8 0 0 1-3.6 0v-.2a1.8 1.8 0 0 0-3.1-1.3l-.1.1a1.8 1.8 0 0 1-2.5-2.5l.1-.1A1.8 1.8 0 0 0 3.3 12a1.8 1.8 0 0 1 0-3.6h.2a1.8 1.8 0 0 0 1.3-3.1l-.1-.1a1.8 1.8 0 0 1 2.5-2.5l.1.1A1.8 1.8 0 0 0 10.4 1.5h.2a1.8 1.8 0 0 1 3.6 0v.2a1.8 1.8 0 0 0 3.1 1.3l.1-.1a1.8 1.8 0 0 1 2.5 2.5l-.1.1A1.8 1.8 0 0 0 21 8.4v.2a1.8 1.8 0 0 1 0 3.6h-.2a1.8 1.8 0 0 0-1.4 2.8Z" stroke="currentColor" strokeWidth="1.7" transform="scale(.72) translate(4.7 4.7)" /></svg>
  if (name === 'sun') return <svg {...common}><circle cx="12" cy="12" r="3.5" stroke="currentColor" strokeWidth="1.6" /><path d="M12 3v2m0 14v2M3 12h2m14 0h2m-3.6-6.4-1.4 1.4M7 17l-1.4 1.4m0-12.8L7 7m10 10 1.4 1.4" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" /></svg>
  if (name === 'moon') return <svg {...common}><path d="M20 15.3A8.2 8.2 0 0 1 8.7 4a8.2 8.2 0 1 0 11.3 11.3Z" stroke="currentColor" strokeWidth="1.7" strokeLinejoin="round" /></svg>
  if (name === 'search') return <svg {...common}><circle cx="10.8" cy="10.8" r="6" stroke="currentColor" strokeWidth="1.7" /><path d="m16 16 4 4" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" /></svg>
  if (name === 'bell') return <svg {...common}><path d="M18 9a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9ZM10 21h4" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" /></svg>
  if (name === 'trend') return <svg {...common}><path d="M5 16 10 11l3 3 6-7" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" /><path d="M15 7h4v4" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" /></svg>
  if (name === 'arrow') return <svg {...common}><path d="M5 12h13m-5-5 5 5-5 5" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" /></svg>
  if (name === 'plus') return <svg {...common}><path d="M12 5v14M5 12h14" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" /></svg>
  if (name === 'chevron') return <svg {...common}><path d="m7 10 5 5 5-5" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" /></svg>
  if (name === 'menu') return <svg {...common}><path d="M4 7h16M4 12h16M4 17h16" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" /></svg>
  return <svg {...common}><path d="m6 6 12 12M18 6 6 18" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" /></svg>
}

function FinoraMark() { return <span className="finora-mark" aria-hidden="true"><span /></span> }
function Card({ children, className = '' }: { children: ReactNode; className?: string }) { return <section className={`panel ${className}`}>{children}</section> }
function PanelTitle({ eyebrow, title, action }: { eyebrow?: string; title: string; action?: string }) { return <div className="panel-title"><div>{eyebrow && <span className="eyebrow">{eyebrow}</span>}<h2>{title}</h2></div>{action && <button className="quiet-button" type="button">{action}<Icon name="arrow" size={14} /></button>}</div> }
function Amount({ value, positive = false }: { value: number; positive?: boolean }) { return <span className={positive ? 'amount positive' : 'amount'}>{positive ? '+' : '-'}${value.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</span> }

function RevenueChart({ compact = false }: { compact?: boolean }) {
  return <div className={`revenue-chart ${compact ? 'compact' : ''}`}><div className="chart-y"><span>$8k</span><span>$6k</span><span>$4k</span><span>$2k</span><span>$0</span></div><svg viewBox="0 0 640 210" preserveAspectRatio="none" aria-label="Revenue and expense trend chart"><defs><linearGradient id="finora-fill" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stopColor="#5577ed" stopOpacity=".2" /><stop offset="1" stopColor="#5577ed" stopOpacity="0" /></linearGradient></defs><path d="M0 158 C50 150 70 130 112 141 S170 117 210 129 S258 82 302 103 S342 89 382 101 S426 56 470 73 S526 43 570 61 S615 28 640 34 V210 H0Z" fill="url(#finora-fill)" /><path d="M0 158 C50 150 70 130 112 141 S170 117 210 129 S258 82 302 103 S342 89 382 101 S426 56 470 73 S526 43 570 61 S615 28 640 34" fill="none" stroke="#5577ed" strokeWidth="3" strokeLinecap="round" /><path d="M0 177 C52 169 72 173 112 164 S170 157 210 169 S263 153 302 160 S344 140 382 152 S430 131 470 141 S523 121 570 130 S610 112 640 116" fill="none" stroke="#aeb7ca" strokeWidth="2" strokeDasharray="5 6" /></svg><div className="chart-x"><span>Apr</span><span>May</span><span>Jun</span><span>Jul</span><span>Aug</span><span>Sep</span></div></div>
}

function DonutChart() { return <div className="donut-wrap"><div className="donut"><div><strong>64%</strong><span>Essentials</span></div></div><div className="donut-legend"><span><i className="dot blue" />Essentials <b>$1,284</b></span><span><i className="dot violet" />Lifestyle <b>$624</b></span><span><i className="dot pale" />Other <b>$208</b></span></div></div> }
function MiniBars() { return <div className="mini-bars-chart"><i style={{ height: '40%' }} /><i style={{ height: '62%' }} /><i style={{ height: '48%' }} /><i style={{ height: '78%' }} /><i style={{ height: '58%' }} /><i style={{ height: '88%' }} /><i style={{ height: '72%' }} /><i style={{ height: '96%' }} /></div> }

function Overview({ onNavigate }: { onNavigate: (screen: Screen) => void }) {
  return <><div className="welcome-row"><div><span className="eyebrow">MONDAY, SEPTEMBER 16, 2025</span><h1>Good morning, Yug<span>.</span></h1><p>Here's your financial overview for this month.</p></div><button className="primary-button" type="button" onClick={() => onNavigate('Transactions')}><Icon name="plus" size={16} /> Add transaction</button></div><div className="stat-grid"><Card className="balance-card"><span className="card-label">Total balance <button className="icon-button" type="button" aria-label="Balance visibility">◉</button></span><strong>$24,680<span>.50</span></strong><small className="positive"><Icon name="trend" size={13} /> 8.4% <em>vs last month</em></small><div className="balance-spark"><i /><i /><i /><i /><i /><i /><i /><i /></div></Card><Card className="stat-card"><span className="card-label">Income</span><strong>$8,420<span>.00</span></strong><small className="positive">+12.8% <em>this month</em></small><div className="stat-bar income-bar" /></Card><Card className="stat-card"><span className="card-label">Expenses</span><strong>$3,184<span>.20</span></strong><small className="negative">-4.2% <em>this month</em></small><div className="stat-bar expense-bar" /></Card><Card className="stat-card"><span className="card-label">Savings</span><strong>$5,235<span>.80</span></strong><small className="positive">62.1% <em>of income</em></small><div className="stat-bar savings-bar" /></Card></div><div className="main-grid"><Card className="chart-panel"><PanelTitle eyebrow="Cash flow" title="Revenue & expenses" action="View report" /><div className="chart-summary"><div><span>Revenue</span><strong>$42,840</strong></div><div><span>Expenses</span><strong>$18,230</strong></div><div className="period-select">Last 6 months <Icon name="chevron" size={13} /></div></div><RevenueChart /></Card><Card className="spending-panel"><PanelTitle eyebrow="This month" title="Spending breakdown" action="Details" /><DonutChart /></Card></div><div className="main-grid lower-grid"><Card className="transactions-panel"><PanelTitle eyebrow="Activity" title="Recent transactions" action="See all" /><TransactionRows limit={4} onNavigate={onNavigate} /></Card><Card className="goal-panel"><PanelTitle eyebrow="On track" title="Savings goal" /><div className="goal-ring"><strong>68<span>%</span></strong></div><p>New studio setup</p><small>$3,400 of $5,000</small><div className="goal-track"><span /></div><button className="quiet-button" type="button">Manage goal <Icon name="arrow" size={14} /></button></Card></div></>
}

function TransactionRows({ limit, onNavigate }: { limit?: number; onNavigate: (screen: Screen) => void }) { return <div className="transaction-list">{transactions.slice(0, limit).map((transaction) => <button className="transaction-row" type="button" key={`${transaction.name}-${transaction.date}`} onClick={() => onNavigate('Transactions')}><span className={`transaction-icon ${transaction.color}`}>{transaction.icon}</span><span className="transaction-name"><strong>{transaction.name}</strong><small>{transaction.category} · {transaction.date}</small></span><Amount value={transaction.amount} positive={transaction.type === 'income'} /><Icon name="chevron" size={15} /></button>)}</div> }

function TransactionsView({ onNavigate }: { onNavigate: (screen: Screen) => void }) {
  const [search, setSearch] = useState('')
  const [category, setCategory] = useState('All categories')
  const filtered = useMemo(() => transactions.filter((item) => (category === 'All categories' || item.category === category) && item.name.toLowerCase().includes(search.toLowerCase())), [category, search])
  return <><PageHeading eyebrow="Your activity" title="Transactions" description="Track your income and spending in one place." action={<button className="primary-button" type="button" onClick={() => onNavigate('Dashboard')}><Icon name="plus" size={16} /> Add transaction</button>} /><Card className="transactions-table-panel"><div className="table-toolbar"><label className="search-box"><Icon name="search" size={17} /><input placeholder="Search transactions" value={search} onChange={(event) => setSearch(event.target.value)} aria-label="Search transactions" /></label><select value={category} onChange={(event) => setCategory(event.target.value)} aria-label="Filter by category"><option>All categories</option><option>Income</option><option>Groceries</option><option>Software</option><option>Travel</option></select><button className="filter-button" type="button">Date <Icon name="chevron" size={14} /></button></div>{filtered.length ? <div className="transaction-table"><div className="table-head"><span>Transaction</span><span>Category</span><span>Date</span><span>Amount</span></div>{filtered.map((item) => <div className="table-row" key={`${item.name}-${item.date}`}><span className="transaction-name"><span className={`transaction-icon ${item.color}`}>{item.icon}</span><strong>{item.name}</strong></span><span>{item.category}</span><span>{item.date}</span><Amount value={item.amount} positive={item.type === 'income'} /></div>)}</div> : <div className="empty-state"><span>No transactions found</span><small>Try a different search or category.</small></div>}</Card></>
}

function PageHeading({ eyebrow, title, description, action }: { eyebrow: string; title: string; description: string; action?: ReactNode }) { return <div className="page-heading"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{description}</p></div>{action}</div> }
function AnalyticsView() { return <><PageHeading eyebrow="Insights" title="Analytics" description="Understand the patterns behind your money." /><div className="main-grid analytics-grid"><Card className="chart-panel"><PanelTitle eyebrow="Performance" title="Net worth over time" /><div className="metric-highlight"><strong>$24,680.50</strong><span className="positive">+18.2% all time</span></div><RevenueChart /></Card><Card className="spending-panel"><PanelTitle eyebrow="Monthly view" title="Income vs expenses" /><div className="analytics-donut"><strong>72%</strong><span>saved this month</span></div><div className="compare-bars"><span><i /><b>Income</b><em>$8,420</em></span><span><i /><b>Expenses</b><em>$3,184</em></span></div></Card></div><div className="main-grid lower-grid"><Card className="transactions-panel"><PanelTitle eyebrow="Categories" title="Where money goes" /><DonutChart /></Card><Card className="chart-panel monthly-panel"><PanelTitle eyebrow="Monthly overview" title="Cash flow trend" /><MiniBars /><div className="chart-x"><span>Apr</span><span>May</span><span>Jun</span><span>Jul</span><span>Aug</span><span>Sep</span></div></Card></div></> }
function PortfolioView() { return <><PageHeading eyebrow="Your investments" title="Portfolio" description="A clear view of your demo investment mix." action={<button className="primary-button" type="button"><Icon name="plus" size={16} /> Add holding</button>} /><div className="portfolio-stats"><Card><span className="card-label">Portfolio value</span><strong>$18,420<span>.80</span></strong><small className="positive">+6.84% all time</small></Card><Card><span className="card-label">Today's return</span><strong className="positive">+$284<span>.12</span></strong><small>+1.56% today</small></Card><Card><span className="card-label">Cash available</span><strong>$2,460<span>.00</span></strong><small>13.4% of portfolio</small></Card></div><Card className="holdings-panel"><PanelTitle eyebrow="Allocation" title="Holdings" action="View allocation" /><div className="holdings-table"><div className="table-head"><span>Asset</span><span>Allocation</span><span>Value</span><span>Return</span></div>{[['US Total Stock Market', 'VTI', '42%', '$7,736.74', '+12.4%'], ['Global Clean Energy', 'ICLN', '24%', '$4,420.99', '+8.1%'], ['Short-Term Treasury', 'SHY', '19%', '$3,497.95', '+3.6%'], ['Cash reserve', 'USD', '15%', '$2,765.12', '—']].map((holding) => <div className="table-row" key={holding[1]}><span><strong>{holding[0]}</strong><small>{holding[1]}</small></span><span>{holding[2]}</span><span>{holding[3]}</span><span className={holding[4].startsWith('+') ? 'positive' : ''}>{holding[4]}</span></div>)}</div></Card></> }
function SettingsView({ darkMode, onToggleTheme }: { darkMode: boolean; onToggleTheme: () => void }) { return <><PageHeading eyebrow="Workspace" title="Settings" description="Make Finora feel like your own." /><div className="settings-grid"><Card><PanelTitle eyebrow="Profile" title="Personal details" /><div className="profile-block"><div className="large-avatar">YL</div><div><strong>Yug Lathiya</strong><p>Demo workspace</p></div><button className="quiet-button" type="button">Edit <Icon name="arrow" size={14} /></button></div></Card><Card><PanelTitle eyebrow="Appearance" title="Interface" /><div className="setting-row"><span><strong>Dark mode</strong><small>Use a darker color palette</small></span><button className={`toggle ${darkMode ? 'is-on' : ''}`} type="button" aria-label="Toggle dark mode" aria-pressed={darkMode} onClick={onToggleTheme}><i /></button></div><div className="setting-row"><span><strong>Compact numbers</strong><small>Shorten large financial values</small></span><button className="toggle" type="button" aria-label="Toggle compact numbers"><i /></button></div></Card><Card><PanelTitle eyebrow="Notifications" title="Stay informed" /><div className="setting-row"><span><strong>Weekly summary</strong><small>Receive a weekly overview</small></span><button className="toggle is-on" type="button" aria-label="Toggle weekly summary"><i /></button></div><div className="setting-row"><span><strong>Payment reminders</strong><small>Get notified before payments</small></span><button className="toggle is-on" type="button" aria-label="Toggle payment reminders"><i /></button></div></Card><Card><PanelTitle eyebrow="Account" title="Preferences" /><div className="setting-row"><span><strong>Currency</strong><small>USD · United States Dollar</small></span><Icon name="chevron" size={16} /></div><div className="setting-row"><span><strong>Data source</strong><small>Local demo data only</small></span><span className="demo-pill">Demo</span></div></Card></div></> }

function App() {
  const [screen, setScreen] = useState<Screen>('Dashboard')
  const [darkMode, setDarkMode] = useState(false)
  const [mobileNav, setMobileNav] = useState(false)
  const navigate = (nextScreen: Screen) => { setScreen(nextScreen); setMobileNav(false) }
  return <div className={`finora-app ${darkMode ? 'dark-mode' : ''}`}><aside className={`sidebar ${mobileNav ? 'mobile-open' : ''}`}><div className="brand"><FinoraMark /><span>finora<small>FINANCIAL ANALYTICS</small></span></div><button className="sidebar-close" type="button" onClick={() => setMobileNav(false)} aria-label="Close navigation"><Icon name="close" /></button><div className="demo-badge">Portfolio concept <i>Demo data</i></div><nav className="side-nav" aria-label="Main navigation">{navItems.map((item) => <button className={screen === item.label ? 'active' : ''} key={item.label} type="button" onClick={() => navigate(item.label)}><Icon name={item.icon} size={18} /><span>{item.label}</span>{screen === item.label && <i className="nav-indicator" />}</button>)}</nav><div className="sidebar-bottom"><button className="sidebar-profile" type="button" onClick={() => navigate('Settings')}><span className="avatar">YL</span><span><strong>Yug Lathiya</strong><small>Demo workspace</small></span><Icon name="chevron" size={15} /></button><p>Fictional dashboard created by<br />Yug Lathiya.</p></div></aside><div className="app-shell"><header className="topbar"><button className="mobile-menu" type="button" onClick={() => setMobileNav(true)} aria-label="Open navigation"><Icon name="menu" /></button><div className="topbar-title"><span>Workspace</span><strong>{screen}</strong></div><div className="topbar-actions"><label className="top-search"><Icon name="search" size={17} /><input aria-label="Global search" placeholder="Search anything" /></label><button className="theme-toggle" type="button" aria-label="Toggle theme" onClick={() => setDarkMode(!darkMode)}><Icon name={darkMode ? 'sun' : 'moon'} size={17} /></button><button className="notification-button" type="button" aria-label="Notifications"><Icon name="bell" size={17} /><i /></button><button className="avatar top-avatar" type="button" onClick={() => navigate('Settings')}>YL</button></div></header><main className="content">{screen === 'Dashboard' && <Overview onNavigate={navigate} />}{screen === 'Transactions' && <TransactionsView onNavigate={navigate} />}{screen === 'Analytics' && <AnalyticsView />}{screen === 'Portfolio' && <PortfolioView />}{screen === 'Settings' && <SettingsView darkMode={darkMode} onToggleTheme={() => setDarkMode(!darkMode)} />}</main><footer className="app-footer">Finora is a fictional portfolio concept by Yug Lathiya. All figures shown are fictional demo data for portfolio purposes.</footer></div></div>
}

export default App
