import { useState, type FormEvent, type ReactNode } from 'react'
import './App.css'

type IconName = 'arrow' | 'spark' | 'layers' | 'cursor' | 'orbit'
type ProjectType = 'aether' | 'luma' | 'orbit'
type Project = { name: string; category: string; description: string; tags: string[]; type: ProjectType }

const services = [
  { number: '01', title: 'Web Design & Development', description: 'Fast, flexible digital homes that make your next chapter feel inevitable.', icon: 'layers' as IconName },
  { number: '02', title: 'UI/UX Design', description: 'Clear, intuitive interfaces built around the moments that matter most.', icon: 'cursor' as IconName },
  { number: '03', title: 'Digital Product Design', description: 'From first sketch to launch day, we shape products people want to use.', icon: 'spark' as IconName },
  { number: '04', title: 'Interactive Experiences', description: 'Thoughtful motion and playful details that turn attention into connection.', icon: 'orbit' as IconName },
]

const projects: Project[] = [
  { name: 'Aether Finance', category: 'FINTECH / PRODUCT DESIGN', description: 'Making money feel a little more human with a calmer way to see what is next.', tags: ['Strategy', 'UI/UX', 'Development'], type: 'aether' },
  { name: 'Luma Commerce', category: 'E-COMMERCE / WEB DESIGN', description: 'A brighter storefront for a new generation of considered everyday goods.', tags: ['Art direction', 'Web design', 'Shopify'], type: 'luma' },
  { name: 'Orbit Analytics', category: 'DATA / DIGITAL PRODUCT', description: 'Turning complex signals into clear decisions for teams that move quickly.', tags: ['Product design', 'Design system', 'React'], type: 'orbit' },
]

function Icon({ name, size = 20 }: { name: IconName; size?: number }) {
  if (name === 'arrow') return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M5 12h13M13 6l6 6-6 6" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" /></svg>
  if (name === 'layers') return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="m12 4 8 4-8 4-8-4 8-4Z M4 12l8 4 8-4 M4 16l8 4 8-4" stroke="currentColor" strokeWidth="1.5" strokeLinejoin="round" /></svg>
  if (name === 'cursor') return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="m5 3 2.4 15.2 3.9-4 4.9 5.8 2-1.7-4.9-5.8 5.5-.9L5 3Z" stroke="currentColor" strokeWidth="1.5" strokeLinejoin="round" /></svg>
  if (name === 'orbit') return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" aria-hidden="true"><ellipse cx="12" cy="12" rx="9" ry="4.2" transform="rotate(-32 12 12)" stroke="currentColor" strokeWidth="1.5" /><circle cx="17.4" cy="7.3" r="1.8" fill="currentColor" /></svg>
  return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="m12 3 1.8 6.2L20 12l-6.2 1.8L12 20l-1.8-6.2L4 12l6.2-2.8L12 3Z" stroke="currentColor" strokeWidth="1.5" strokeLinejoin="round" /></svg>
}

function Mark() { return <span className="mark" aria-hidden="true"><span /></span> }

function Button({ children, dark = false, href = '#contact' }: { children: ReactNode; dark?: boolean; href?: string }) {
  return <a className={`button ${dark ? 'button-dark' : ''}`} href={href}>{children}<Icon name="arrow" size={17} /></a>
}

function ProductVisual() {
  return <div className="hero-visual" aria-label="Abstract preview of a digital product interface">
    <div className="visual-note">NEXA / 2025 <span>↗</span></div><div className="visual-orbit orbit-one" /><div className="visual-orbit orbit-two" />
    <div className="dashboard-card"><div className="dash-top"><span className="dash-brand"><Mark /> aether</span><span className="dash-avatar">KS</span></div><div className="dash-copy"><span>Good morning, Kira</span><strong>Your momentum is <em>up.</em></strong></div><div className="chart"><span className="chart-label">TOTAL BALANCE <b>$84,250.00</b></span><svg viewBox="0 0 320 100" preserveAspectRatio="none" aria-hidden="true"><path d="M0 78 C28 72 38 79 56 61 S83 70 100 48 S134 58 151 34 S179 57 195 41 S224 50 242 20 S267 45 286 27 S305 27 320 7" fill="none" stroke="currentColor" strokeWidth="3" /></svg><div className="chart-axis"><span>APR 01</span><span>APR 30</span></div></div><div className="dash-bottom"><span>↑ 12.4% this month</span><b>View insights <Icon name="arrow" size={13} /></b></div></div>
    <div className="visual-pill"><span className="pill-dot" /> Built for better</div><div className="visual-stamp">N</div>
  </div>
}

function ProjectVisual({ type }: { type: ProjectType }) {
  return <div className={`project-visual ${type}`}>
    {type === 'aether' && <><div className="mini-nav">aether <span>•••</span></div><div className="mini-balance">$84,250 <small>+12.4%</small></div><div className="mini-bars"><i /><i /><i /><i /><i /><i /><i /></div><div className="mini-line" /></>}
    {type === 'luma' && <><div className="luma-word">luma</div><div className="luma-sun" /><div className="luma-product">everyday, elevated <span>↗</span></div></>}
    {type === 'orbit' && <><div className="orbit-header"><span>ORBIT / OVERVIEW</span><b>Q2 2025</b></div><div className="orbit-number">72.8 <small>+8.6%</small></div><div className="orbit-grid"><i /><i /><i /><i /><i /><i /></div><div className="orbit-circle">◎</div></>}
  </div>
}

function ProjectCard({ project, onOpen }: { project: Project; onOpen: (project: Project) => void }) {
  return <article className="project"><button type="button" className="project-card" aria-label={`View case study for ${project.name}`} onClick={() => onOpen(project)}><div className="project-card-preview"><ProjectVisual type={project.type} /></div><div className="project-info"><div className="project-heading"><p className="project-category">{project.category}</p><span className="concept-label">Concept project</span></div><h3>{project.name}</h3><p>{project.description}</p><div className="project-meta"><div>{project.tags.map((tag) => <span key={tag}>{tag}</span>)}</div><span className="project-link">View case study <Icon name="arrow" size={15} /></span></div></div></button></article>
}

function App() {
  const [menuOpen, setMenuOpen] = useState(false)
  const [selectedProject, setSelectedProject] = useState<(typeof projects)[number] | null>(null)
  const [contactStatus, setContactStatus] = useState('')

  const closeMenu = () => setMenuOpen(false)
  const openProject = (project: (typeof projects)[number]) => setSelectedProject(project)
  const handleContactSubmit = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault()
    setContactStatus('Thanks, your message is ready. This demo does not send data to a backend.')
  }

  return (
    <main>
      <header className="site-header"><a className="wordmark" href="#top" aria-label="Nexa Digital Solutions home" onClick={closeMenu}><Mark /><span>NEXA<small>DIGITAL SOLUTIONS</small></span></a><button type="button" className="menu-toggle" aria-label="Toggle navigation" aria-expanded={menuOpen} onClick={() => setMenuOpen(!menuOpen)}><span /><span /></button><nav className={menuOpen ? 'is-open' : ''} aria-label="Primary navigation"><a href="#top" onClick={closeMenu}>Home</a><a href="#services" onClick={closeMenu}>Services</a><a href="#work" onClick={closeMenu}>Work</a><a href="#about" onClick={closeMenu}>About</a><a href="#contact" onClick={closeMenu}>Contact</a><Button>Start a project</Button></nav></header>
      <section className="hero section-wrap" id="top"><div className="hero-copy"><p className="eyebrow"><span /> Independent digital studio / 2025</p><p className="demo-label">Portfolio demo by Yug Lathiya</p><h1>Digital experiences built to move <span>businesses forward.</span></h1><p className="hero-lede">We design and build high-performance websites and digital products that look exceptional, work beautifully, and turn ideas into meaningful experiences.</p><div className="hero-actions"><Button dark href="#work">View our work</Button><a className="text-link" href="#contact">Start a project <Icon name="arrow" size={16} /></a></div></div><ProductVisual /><div className="scroll-cue"><span>Scroll to explore</span><i /></div></section>
      <section className="intro section-wrap"><p className="section-kicker">01 / The studio</p><div className="intro-content"><h2>We make the <span>complex</span><br />feel clear.</h2><div><p>Nexa is a digital design and development studio for ambitious teams. We combine sharp strategy, expressive design, and dependable technology to create work that earns attention and drives action.</p><a className="text-link" href="#about">More about Nexa <Icon name="arrow" size={16} /></a></div></div></section>
      <section className="services section-wrap" id="services"><div className="section-heading"><div><p className="section-kicker">02 / What we do</p><h2>Built for the <span>next move.</span></h2></div><p>Good work starts with a good question.<br />We bring the right ones to the table.</p></div><div className="service-grid">{services.map((service) => <article className="service-card" key={service.number}><div className="service-top"><span>{service.number}</span><span className="service-icon"><Icon name={service.icon} size={23} /></span></div><h3>{service.title}</h3><p>{service.description}</p><a href="#contact" aria-label={`Learn more about ${service.title}`}><Icon name="arrow" size={18} /></a></article>)}</div></section>
      <section className="work section-wrap" id="work"><div className="section-heading"><div><p className="section-kicker">03 / Selected work</p><h2>A few things <span>we've made.</span></h2></div><p>Strategy with a point of view.<br />Design with a job to do.</p></div><div className="project-list">{projects.map((project) => <ProjectCard key={project.name} project={project} onOpen={openProject} />)}</div><p className="demo-note">Fictional project concepts created for this portfolio demonstration.</p></section>
      <section className="process section-wrap"><div className="process-heading"><p className="section-kicker">04 / How we work</p><h2>A clear path from <span>thought</span> to thing.</h2></div><div className="process-list">{['Discover', 'Define', 'Design', 'Develop', 'Launch'].map((step, index) => <div className="process-step" key={step}><span>0{index + 1}</span><strong>{step}</strong><i /></div>)}</div></section>
      <section className="about section-wrap" id="about"><div className="about-mark"><Mark /><span>YUG<br />LATHIYA</span></div><div className="about-copy"><p className="section-kicker">05 / About Yug</p><h2>Designing with<br /><span>purpose.</span></h2><p>Yug Lathiya is a Front-End Web Designer &amp; Developer and UI/UX Designer who combines frontend development with visual design to create responsive, user-friendly digital experiences.</p><p className="about-role">Front-End Web Designer &amp; Developer<br />UI/UX Designer</p><p className="about-strengths">Core strengths: frontend development, UI/UX design, responsive web design, React.js, TypeScript, Figma, Adobe XD, and visual design.</p><a className="text-link" href="#contact">Let's work together <Icon name="arrow" size={16} /></a></div></section>
      <section className="experience section-wrap" id="experience"><div className="experience-heading"><p className="section-kicker">06 / Experience</p><h2>Experience</h2><p>Nexa Digital Solutions is a fictional concept project created as part of Yug Lathiya's portfolio.</p></div><div className="experience-content"><article className="experience-entry"><div className="experience-meta"><span>March 2023 — June 2026</span><span>Surat, Gujarat</span></div><div className="experience-role"><p className="experience-company">Webmint Infotech</p><h3>Front-End Web Designer &amp; Developer</h3><ul><li>Designed and developed responsive, user-friendly websites and web applications.</li><li>Used HTML, CSS, JavaScript, TypeScript, React.js and Bootstrap.</li><li>Translated Figma and Adobe XD wireframes/mockups into pixel-accurate frontend interfaces.</li><li>Created UI/UX designs, graphics and visual assets using Adobe Illustrator and Photoshop.</li><li>Collaborated with clients and team members to deliver polished web experiences.</li><li>Focused on detail, quality and maintainable frontend code.</li></ul></div></article><aside className="skills"><p className="section-kicker">Skills &amp; tools</p><div><h3>Frontend</h3><p>HTML, CSS, JavaScript, TypeScript, React.js, Bootstrap</p></div><div><h3>Design</h3><p>UI/UX Design, Figma, Adobe XD, Illustrator, Photoshop, Responsive Web Design</p></div><div><h3>Additional</h3><p>Web3 Basics, Cryptography, Blockchain Fundamentals</p></div></aside></div></section>
      <section className="proof section-wrap"><div className="stats"><div><strong>25<span>+</span></strong><p>Projects</p></div><div><strong>3<span>+</span></strong><p>Years experience</p></div><div><strong>15<span>+</span></strong><p>Clients</p></div><div><strong>100<span>%</span></strong><p>Focus on quality</p></div></div><p className="proof-note">Portfolio demonstration content. Not real Nexa business statistics.</p><div className="testimonials"><article><span className="quote-mark">“</span><blockquote>Nexa found the signal in a very noisy brief. The result feels simple, but every decision is doing real work.</blockquote><p><b>Alex Morgan</b><br />Founder, Aether Finance <em>Sample portfolio testimonial</em></p></article><article><span className="quote-mark">“</span><blockquote>They brought a rare mix of taste and rigour. We launched with confidence and a product our team loves to use.</blockquote><p><b>Rina Patel</b><br />Product lead, Orbit Analytics <em>Sample portfolio testimonial</em></p></article></div></section>
      <section className="contact section-wrap" id="contact"><div className="contact-intro"><p className="section-kicker">07 / Contact Yug</p><h2>Let's build<br /><span>something great.</span></h2><p>Have a project, opportunity, or idea in mind? I'd love to hear about it.</p><div className="contact-links"><a href="mailto:yuglathiya2814@gmail.com"><span>Email</span>yuglathiya2814@gmail.com</a><a href="https://linkedin.com/in/yug2814" target="_blank" rel="noopener noreferrer"><span>LinkedIn</span>linkedin.com/in/yug2814</a><a href="https://github.com/yug2814" target="_blank" rel="noopener noreferrer"><span>GitHub</span>github.com/yug2814</a></div></div><form className="contact-form" onSubmit={handleContactSubmit}><div className="form-row"><label htmlFor="contact-name">Name</label><input id="contact-name" name="name" type="text" autoComplete="name" required /></div><div className="form-row"><label htmlFor="contact-email">Email</label><input id="contact-email" name="email" type="email" autoComplete="email" required /></div><div className="form-row"><label htmlFor="contact-subject">Subject</label><input id="contact-subject" name="subject" type="text" required /></div><div className="form-row"><label htmlFor="contact-message">Message</label><textarea id="contact-message" name="message" rows={4} required /></div><button className="button button-dark" type="submit">Send message <Icon name="arrow" size={17} /></button>{contactStatus && <p className="form-status" role="status" aria-live="polite">{contactStatus}</p>}</form></section>
      <footer className="footer section-wrap"><div className="footer-brand"><a className="wordmark" href="#top" onClick={closeMenu}><Mark /><span>NEXA<small>DIGITAL SOLUTIONS</small></span></a><p>Concept project by Yug Lathiya</p></div><div className="footer-links"><div><span>Navigation</span><a href="#top" onClick={closeMenu}>Home</a><a href="#services" onClick={closeMenu}>Services</a><a href="#work" onClick={closeMenu}>Work</a><a href="#about" onClick={closeMenu}>About</a><a href="#contact" onClick={closeMenu}>Contact</a></div><div><span>Social</span><a href="https://linkedin.com/in/yug2814" target="_blank" rel="noopener noreferrer">LinkedIn</a><a href="https://github.com/yug2814" target="_blank" rel="noopener noreferrer">GitHub</a></div></div><p className="copyright">© 2026 Yug Lathiya. All rights reserved.</p></footer>
      {selectedProject && <div className="dialog-backdrop" role="presentation" onClick={() => setSelectedProject(null)}><section className="project-dialog" role="dialog" aria-modal="true" aria-labelledby="project-dialog-title" onClick={(event) => event.stopPropagation()}><button type="button" className="dialog-close" aria-label="Close project details" onClick={() => setSelectedProject(null)}>×</button><p className="project-category">{selectedProject.category}</p><h2 id="project-dialog-title">{selectedProject.name}</h2><p>{selectedProject.description} This is a fictional case study concept created to demonstrate Nexa's approach across strategy, design, and technology.</p><div className="dialog-tags">{selectedProject.tags.map((tag) => <span key={tag}>{tag}</span>)}</div><a className="button button-dark" href="#contact" onClick={() => setSelectedProject(null)}>Discuss a similar project <Icon name="arrow" size={17} /></a></section></div>}
    </main>
  )
}

export default App
